const List<String> iosSounds = [
  "air_raid_siren.m4a",
  "blue_brick.m4a",
  "eee_ooo.m4a",
  "electronic_ringer.m4a",
  "emergency_alarm.m4a",
  "future_alarm.m4a",
  "industrial_alarm.m4a",
  "reggae.m4a",
  "rotary_phone.m4a",
  "school_fire_alarm.m4a",
  "sparrow_alarm.m4a",
  "voriko.m4a",
  "wakey_wakey.m4a",
];
